### ISSUE TITLE
Error setting phoneme callback on Mac.

### ISSUE THREAD

**Issue by trypsynth** [pitermach/Love2talk#1]
On macOS 13 (Ventura) there's been a problem for a while where anything that uses NSSpeechSynthesizer spams STDERR with the following:

```shell
NSSpeechSynthesizer: [NSSpeechSynthesizer _setupCallbacks] - NSSpeechSynthesizer: Error setting soPhonemeCallBack
```

To fix this in TDSR, I added this line to the QueuedSynth class:

```python
	def speechSynthesizer_willSpeakPhoneme_(self, synth, phoneme): return
```

Should we file a bug upstream in the Obj-C repository about this? I'm not sure if it's apple's doing, but I'd assume so, as I reported this on beta 1 and still nothing, so am assuming its intentional

**Comment by pitermach** [comment]
It'll probably be a few days until I can take a proper look at this, but that's really interesting since I don't use that precise callbacks anywhere in the code. You might be able to do a similar function override in lua as well.

There's probably little point reporting this to the OBJCLua developer since I don't think that's technically what's causing the problem here.

Perhaps this is the impulse I needed to rewrite the mac code to use AVSpeechSynthesizer instead assuming that doesn't cause this problem. It also gives us things like queuing for free and anything that gets spoken with it also gets brailled by VoiceOver. I wrote a dirty prototype a while ago which I'll look into working on. The AVSpeech API used to have some issues on Monterey and Big Sur like utterances not getting any voice set on them, but in Ventura some apps that use it like System Fault which used to be broken started working right so now may be the right time to look at it again.

**Comment by trypsynth** [comment]
It doesn't really matter if you use it, I think they changed something in Ventura that makes NSSpeechSynthesizer look for it (most likely related to the new AVSpeechSynthesisProviderAudioUnit work).

AVSpeechSynthesizer actually has a decent API. I've not toyed with objc in Lua, but I was playing with AVSpeechSynthesizer in Objective-C itself a few days ago. Pretty simple usage AFAIK. Something like
```objc
AVSpeechSynthesizer *synth = [[AVSpeechSynthesizer] alloc] init];
// Make it shut up before speaking anything else.
[synth stopSpeakingAtBoundary:0];
// Speak hi.
AVSpeechUtterance *utterance = [[AVSpeechUtterance alloc] initWithText:@"Hi"];
[synth speakUtterance:utterance];
```
The only thing I was unable to figure out from my testing was how to get/set the voice, but I didn't really try that hard
